### PR TITLE
A new "New activity" image, in Arabic

### PR DESCRIPTION
**Pull request by nadavkav**
Hi Gareth,

Sending you a cool looking image of "New activity" in Arabic, for your "collection" ;-)
Please see if you can PR it.

Nadav

### CODE REVIEW

**Comment by gjb2048** [comment]
Thanks Nadav, but does not look the same as https://translate.google.co.uk/#auto/ar/new%20activity ?

**Comment by nadavkav** [comment]
Well...
Only in Israel, we have about 3-5 different "types" of Arabic languages. where all in all there are [around 30](https://en.wikipedia.org/wiki/ISO_639_macrolanguage#ara) different types. not sure if the correct way is to call it dialects or actual languages or not, but they are different. They all use the same glyphs but they pronounce it differently and also have different words to describe the same meaning.
I can definitely say that you might get a different PR from a different Arabic speaking group. but this is a good start :smile:

**Comment by gjb2048** [comment]
Ok, but as things stand then at the moment I'm unwilling to distribute words in a language I don't understand and might therefore cause inadvertent offence too.  Everything globally is volatile at the moment.

People are clearly free to add their own image if they want locally.

**Comment by nadavkav** [comment]
I completely agree.
How about dropping the images in favor of a get_string('newactivity', 'format_grid') + div:transform: rotate(...) ?

**Comment by gjb2048** [comment]
No.  As it means more work / maintenance for me for the sake of adding one image.

**Pull request closed without merging**
