### PR TITLE
Attempt to fix the tooltip accessibility issue 

### PR DESCRIPTION
**Pull request by pgogy**
Leave title in place
add Screen reader only bit to image section

### CODE REVIEW

**Comment by gjb2048** [comment]
Hi Pat,

Thanks for the patch, but:

- What is the exact nature of the problem that it fixes with supporting evidence.
- Why have you removed 'core_text::'.

please.

Gareth

**Comment by gjb2048** [comment]
Plus you need to address the issues raised by the TravisCI checks.

**Comment by pgogy** [comment]
Hello
The issue is (sorry I forgot to list as an issue) as I was a bit arrogant and assumed this fix would work :)
The tooltips which appear when you hover over a link are only accessible via the hover (as I assume the JS file) takes the title attribute content out and then changes it to data-tooltip-title. As such anyone with accessibility requirements who needs the title attribute who doesn't use tech which facilitates hover or focus can't access the tooltip. The SR-Only bit was extra (and perhaps spurious) but it felt handy to cover bases the JS change may miss. 
I am not sure why i removed core text either, so I will look into that.
I've also no experience using Travis, so I can't fathom how to interpret the failure. For this I am sorry, but I am keen to get this patch added in if possible. Links to travis guidance appreciated and so on.
Thanks
Pat

**Comment by gjb2048** [comment]
Hi Pat,

Ok, so in a nutshell the problem you're saying is that the tooltip text is not view-able to screen readers?  How do you draw this conclusion please?  Where is the evidence?

With Travis, just follow the links until you reach the report, then read: https://travis-ci.org/gjb2048/moodle-format_grid/jobs/289049155.

You don't have to list it as an issue, but please I do need to know 'why' so that I can make the best judgement of the reason and therefore suitability of the code in solving that problem.

Kind regards,

Gareth

**Comment by gjb2048** [comment]
P.S. What accessibility tool are you using to prove a before failure and after fix?

**Comment by pgogy** [comment]
I am helping University College London (UCL) and they've engaged Blazie (who make the jaws screen reader software). It is a 1000 pounds for the software, and I don't have it to test with. I will get their text and share it directly.

**Comment by gjb2048** [comment]
Ok....

To me: echo html_writer::tag('div', "accessibletooltip", array("class"=>"sr-only")); - looks pointless.
The JS does not need to change because its affecting the already generated markup.
The $summary is not needed, instead: $content .= html_writer::tag('p', str_replace("&nbsp;", ' ', strip_tags($thissection->summary)), array('class' => 'sr-only'));

So in reality a one line fix.

**Comment by gjb2048** [comment]
But then as the existing tooltip 'div' is not hidden, then why is it not read out already?

**Comment by pgogy** [comment]
It's not just screen readers - sorry today isn't a work day for me (looking after child) so I'll post what they said first thing tomorrow and see about sorting the code out

**Comment by pgogy** [comment]
Closing this as have a new one

**Comment by gjb2048** [comment]
New patch Pat?

FYI - Grid tooltip is this: https://getbootstrap.com/docs/3.3/javascript/#tooltips = therefore BS 3.3.7 is wrong accessibility wise?

**Comment by gjb2048** [comment]
On in effect in reading the doc's, just need to add a 'tabindex="0"'.

**Comment by pgogy** [comment]
Yeah - but i am not sure it is better, Hence raising issue. Been on it all day and not got that far. Wanted to show willing though. 

Have messed up my repo so making a new one

**Comment by pgogy** [comment]
tabindex=0 can make things go a bit weird

**Pull request closed without merging**
