### PR TITLE
Add RTL/LTR support for arrows nagivation

### PR DESCRIPTION
**Pull request by nadavkav**
Hi Gareth,
Just making the arrow navigation of the overlay popup feel more comfortable to RTL folks ;-)

Please review and consider adding.
(btw, if you have a better way to detect RTL mode with JS and YUI... please advise)

Nadav

### CODE REVIEW

**Comment by gjb2048** [comment]
Thanks Nadav.  I'll review more soon.  Initial thought is to pass in result of right_to_left() as a parameter to the 'init' method.  But my mind seems to think there is an M. thing for RTL already.

**Comment by gjb2048** [comment]
Merged then will adapt.

**Comment by gjb2048** [comment]
Arrrggghhhh!!! Was non MOODLE_28 and not master!!!  Had to revert.  Enhancements on 'master' for M2.9 only please.

**Comment by gjb2048** [comment]
Ok, implemented in master in: https://github.com/gjb2048/moodle-format_grid/commit/05ee6a45acd26e76c39b1ab4ea5faf59abdc433d - credit by cherry-picking original commit in: https://github.com/gjb2048/moodle-format_grid/commit/317e9151d6ea59ce1117b56e6f57157e2cf650f6

**Comment by nadavkav** [comment]
Bless you. (sorry for that M28 wrong branch fix) 
If you'll find that M.rtl , please share :-)

**Comment by gjb2048** [comment]
Hi Nadav,

I think with the departure of YUI, I'm keen to keep things as simple and upgradable as possible :).

Cheers,

Gareth

**Pull request merged**
