### PR TITLE
French version of the new activity image -  modified version

### PR DESCRIPTION
**Pull request by Momardiakhate**
Hi Gareth,
Here I send the other french version of the new activity image.
Please take a look and add  if you think it is ok.
Regards 
Momar

### CODE REVIEW

**Comment by gjb2048** [comment]
Merci Momar,

As the branch has conflicts, please rebase master and ensure that the pull contains a single commit.

Gareth

**Comment by Momardiakhate** [comment]
Hi Gareth,
Thanks again. I tried to rebase the master as explained in the Github help
doc. I don't know whether it works or not.  Sorry for my ignorance i am not
very familiar with this kind of issue:). The change is in the branch
new-activity-fr-label-2.
Thanks
Momar

Le 14 nov. 2018 6:30 PM, "Gareth J Barnard" <notifications@github.com> a
écrit :

Merci Momar,

As the branch has conflicts, please rebase master and ensure that the pull
contains a single commit.

Gareth

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/gjb2048/moodle-format_grid/pull/81#issuecomment-438768217>,
or mute the thread

**Comment by gjb2048** [comment]
Ok Momar, I'll work something out and credit you.

**Comment by gjb2048** [comment]
Hi Momar,

Updated in https://github.com/gjb2048/moodle-format_grid/commit/7d5fa1704614d983a4e45d0b863f89acd6117706.

Kind regards,

Gareth

**Comment by Momardiakhate** [comment]
Hi Gareth,
Thank you so much again and have a nice day.
Momar

Le jeu. 15 nov. 2018 1:39 PM, Gareth J Barnard <notifications@github.com> a
écrit :

**Pull request closed without merging**
