### PR TITLE
An attempt to allow for tab focus to work for this format

### PR DESCRIPTION
**Pull request by pgogy**
So using the format as is, tabbing onto the topic title doesn't bring up the tooltip

Roughly what i've done

1) Moved the tooltip titles and so on onto the A element 
2) Altered the CSS to style the tooltip in its new location
3) Done some tweaking in the JS to sort out the focus event firing

No software i've found (chrome extension) throws errors, so I've been shift tabbing and tabbing through the format to test.

Sorry if this is a mess, I've ran it through code checker and tried to make sure the new bits aren't out there.

Been at it for about 5 hours and tried to be sensitive to other uses while making it more accessible

### CODE REVIEW

**Comment by gjb2048** [comment]
Ok, renderer.php errors need fixing: https://travis-ci.org/gjb2048/moodle-format_grid/jobs/290677440

**Comment by gjb2048** [comment]
Hi Pat,

Are you using an IDE?

G

**Comment by gjb2048** [comment]
Ok....

Things not needed to change:

https://github.com/gjb2048/moodle-format_grid/pull/61/commits/7ffcabd8f2211205c2f06f02bbe7ad5bcaaa67c2#diff-3c999c21a9c3b6b299f13a9b416b5768R14

https://github.com/gjb2048/moodle-format_grid/pull/61/commits/7ffcabd8f2211205c2f06f02bbe7ad5bcaaa67c2#diff-3c999c21a9c3b6b299f13a9b416b5768R146

https://github.com/gjb2048/moodle-format_grid/pull/61/commits/7ffcabd8f2211205c2f06f02bbe7ad5bcaaa67c2#diff-3c999c21a9c3b6b299f13a9b416b5768R178

https://github.com/gjb2048/moodle-format_grid/pull/61/commits/7ffcabd8f2211205c2f06f02bbe7ad5bcaaa67c2#diff-3c999c21a9c3b6b299f13a9b416b5768R242

https://github.com/gjb2048/moodle-format_grid/pull/61/commits/7ffcabd8f2211205c2f06f02bbe7ad5bcaaa67c2#diff-3c999c21a9c3b6b299f13a9b416b5768R245

https://github.com/gjb2048/moodle-format_grid/pull/61/commits/7ffcabd8f2211205c2f06f02bbe7ad5bcaaa67c2#diff-3c999c21a9c3b6b299f13a9b416b5768R313 - white space at end of line :(

https://github.com/gjb2048/moodle-format_grid/pull/61/commits/7ffcabd8f2211205c2f06f02bbe7ad5bcaaa67c2#diff-3c999c21a9c3b6b299f13a9b416b5768R500 - debugging!  Don't use 'console' use 'log.debug' if needed.  Please read and understand the code.

https://github.com/gjb2048/moodle-format_grid/pull/61/commits/7ffcabd8f2211205c2f06f02bbe7ad5bcaaa67c2#diff-25eb2cfd41b242f700f7c778c4416c17R672

https://github.com/gjb2048/moodle-format_grid/pull/61/commits/7ffcabd8f2211205c2f06f02bbe7ad5bcaaa67c2#diff-25eb2cfd41b242f700f7c778c4416c17R748

https://github.com/gjb2048/moodle-format_grid/pull/61/commits/7ffcabd8f2211205c2f06f02bbe7ad5bcaaa67c2#diff-25eb2cfd41b242f700f7c778c4416c17R791

https://github.com/gjb2048/moodle-format_grid/pull/61/commits/7ffcabd8f2211205c2f06f02bbe7ad5bcaaa67c2#diff-25eb2cfd41b242f700f7c778c4416c17R834

And....

What does this: https://github.com/gjb2048/moodle-format_grid/pull/61/commits/7ffcabd8f2211205c2f06f02bbe7ad5bcaaa67c2#diff-3c999c21a9c3b6b299f13a9b416b5768R253 do please?

And... testing wise, have you checked all four tooltip inside positions and the outside ones too?

Ta,

Gareth

**Comment by pgogy** [comment]
Ok, will do monday. 
Never found an IDE i liked enough to use, will sort out whitespace and line endings

-------- Original message --------

**Comment by pgogy** [comment]
Sorry i did run the moodle code checker but guessing the repo messing up made some mistakes 
Apologies
Re tooltip positions - didn't know there was - this is a setting for the format?

-------- Original message --------

**Comment by gjb2048** [comment]
Hi Pat,

Did the report also highlight this: https://moodle.org/mod/forum/discuss.php?d=356300 ?

Thanks,

Gareth

**Comment by pgogy** [comment]
That looks like the WAVE chrome extension. Nothing else came up on grid i think bit will go into this tomorrow when fixing

-------- Original message --------

**Comment by gjb2048** [comment]
Hi Pat,

Can you clean up the commits please so that there is one commit per issue, as I may have to backport and therefore need to cherry pick as needed.

G

**Comment by pgogy** [comment]
Ok, will try. Not great with git

-------- Original message --------

**Comment by pgogy** [comment]
Trying again

**Pull request closed without merging**
