### PR TITLE
New pull request

### PR DESCRIPTION
**Pull request by pgogy**
Hope this is better

I've made some changes to tooltip to make left work like right does.

I've solved the moodle link you sent by adding in an alt attribute which mirrors aria-label

Sorry if I have gone wrong again

### CODE REVIEW

**Comment by gjb2048** [comment]
Thanks Pat, still needs compressing into a minimal number of commits.  Lots of paid work to do at the moment so this will have to wait.

**Comment by pgogy** [comment]
If you can tell me what you need me to do or point me to some reading happy to help

-------- Original message --------

**Comment by pgogy** [comment]
I tried squashing the commits - hope this helps

**Comment by gjb2048** [comment]
Hi Pat,

Ok, lots of commits now: https://github.com/gjb2048/moodle-format_grid/pull/62/commits.  So I use TortoiseGit to 'combine' commits then do a forced update.  Not sure how to sort out this mess except by creating a new branch for this pull to go into then sorting it there before master.  Or not pull this request but have your repository as a repo and then cherry pick the commits singularly.  Needs time.  Or you create a new branch for a new pull and then make two single commits with the changes required again but learning from this what is not needed.

G

**Comment by gjb2048** [comment]
P.S.  I'm not being annoying with this, just need it neat and manageable, just like the Moodle tracker commits.

**Comment by pgogy** [comment]
Tried to squish again but git is just annoying me
going to close this one and try again

**Pull request closed without merging**
