### PR TITLE
WCAG Changes and work to allow tooltip appearance on hover

### PR DESCRIPTION
**Pull request by pgogy**
Hopefully this works better
I tried making patches from one repo and patched them onto another

Fingers crossed

### CODE REVIEW

**Comment by gjb2048** [comment]
Thanks Pat,

Please could you address these issues: https://travis-ci.org/gjb2048/moodle-format_grid/jobs/293334352#L800-L811 - I know its TravisCI, but you could always run 'Code checker' (https://moodle.org/plugins/local_codechecker) and get the same sort of information.

G

**Comment by gjb2048** [comment]
Also: https://travis-ci.org/gjb2048/moodle-format_grid/jobs/293334352#L689 and https://travis-ci.org/gjb2048/moodle-format_grid/jobs/293334352#L578-L584

**Comment by gjb2048** [comment]
And missing spaces here: https://github.com/gjb2048/moodle-format_grid/pull/63/commits/bb09f09eebb99ab601a533c4a0836147cd2c23ac#diff-3c999c21a9c3b6b299f13a9b416b5768R271

**Comment by pgogy** [comment]
Will do but sometimes the code checker and travis conflict 

-------- Original message --------

**Comment by pgogy** [comment]
Ok, new code in, assuming this will update

**Comment by gjb2048** [comment]
Ok Pat, merging then will correct the issues.

**Comment by gjb2048** [comment]
P.S. Did you test the JS AMD by doing a 'grunt amd' to make the build version?

**Comment by gjb2048** [comment]
Sorry Pat, but going to remove:

````
            if (placement == "left") {
                css.width = (this.getPosition().left <= 100 ) ? 150 : this.getPosition().left;
            }
````
as it looks terrible:

grid_63_1

as against:

grid_63_2

**Comment by pgogy** [comment]
Sorry I never got these emails. Never done a grunt before. No need to apologise :)
Do you need anything from me?

**Comment by gjb2048** [comment]
Hi Pat,

No worries.  Only see my comments about the JS I had to remove.

G

**Comment by gjb2048** [comment]
Also, when changing the JS in future, please read the top of Gruntfile.js that explains everything to do with JS AMD compilation etc.

**Comment by gjb2048** [comment]
And if TDM is off you'll need to do a purge all caches.

**Pull request merged**
