### PR TITLE
Add option to fit content popup to window size

### PR DESCRIPTION
**Pull request by antriver**
With the option enabled, the content box scrolls instead of the page scrolling.

### Example
Off:
Off
On:
On

### CODE REVIEW

**Comment by gjb2048** [comment]
Thank you Anthony for the functionality.

Looking at: https://github.com/antriver/moodle-format_grid/blob/40e789b3c995f830b9c292e77b831e4aafd9e46a/module.js#L317-L319 - this does not need to happen because the initialize_shadebox function is only called when editing is off, therefore if the 'fit_to_window' exists, then do nothing else as before.  The class 'fit_to_window_enabled' is redundant.

**Comment by antriver** [comment]
Hi,
The reason for the two classes is because there are styles in styles.css that apply to .fit_to_window (it makes more sense to put styles in the css rather than in the js like the default style does).
If .fit_to_window was applied in the php rather than the js, the box would have those styles (e.g. position:fixed) all the time, even if editing is enabled.

**Comment by gjb2048** [comment]
Thanks for the reply.  I'll sleep on it.

I know I need to do the same, but Code Checker would winge about missing space after colon: https://github.com/antriver/moodle-format_grid/blob/40e789b3c995f830b9c292e77b831e4aafd9e46a/styles.css#L185-L186

**Comment by antriver** [comment]
Whoops, good catch. I've fixed that now

**Comment by gjb2048** [comment]
Thanks Anthony,

If I may I'll merge and pull early this week.  Late here now.  So I can update the Readme.md file, what credit and back story would you like?

Kind regards,

Gareth

**Comment by antriver** [comment]
Thanks!
Just my name and link to my website would be appreciated :)
Anthony Kuske [www.anthonykuske.com](www.anthonykuske.com)

**Comment by gjb2048** [comment]
Hi Anthony,

Sorry, I've not forgotten about this, just very busy with iMoot 2015.

It occurs to me that the renderer could add the class 'fit_to_window' only if editing was off, then 'fit_to_window_enabled' would not be needed.

Also I like the idea of having more in the CSS, so perhaps there could be a reduction in the JS generated stuff.

Cheers,

Gareth

**Comment by gjb2048** [comment]
Hi Anthony,

Tidy up, improve and add reset option: https://github.com/gjb2048/moodle-format_grid/commit/e1b3a864a366b56d56bf48c8ca96b8f4022716a4

Cheers,

Gareth

**Pull request merged**
