### PR TITLE
Added the ability to grey out and unlink grid icons for unavailable sections

### PR DESCRIPTION
**Pull request by justinhunt**
This will apply a css class "inaccessible" to the icon and remove the link if the section is unavailable.
There is a setting on the course format options and the admin settings to turn this on or off. The setting is called "greyouthidden"

It does not fully implement reset functionality, and there is no capability yet for the setting. Do with it what you will, but thanks for all your work on this. it made my head spin.

### CODE REVIEW

**Comment by gjb2048** [comment]
Thanks Justin,

Does this fix this: https://github.com/gjb2048/moodle-format_grid/issues/28 ?

Kind regards,

Gareth

**Comment by justinhunt** [comment]
I don't think it fixes that. But it kind of covers it up because they won't
get as far as that.
The icons go grey and no links are generated for them, when the
section/topic is unavailable.

Justin

**Comment by gjb2048** [comment]
Thanks Justin,

This looks complex and my mind is full of themes at the moment.  I'll look at this as soon as I can.

Kind regards,

Gareth

**Comment by justinhunt** [comment]
I know that feeling. No hurry on my part. Thanks again

**Comment by gjb2048** [comment]
Cannot seem to make this work in 'master' when the section is unavailable.

**Comment by justinhunt** [comment]
I've only tested it on one site, well two, but they are really just clones of each other. So I guess it's just not getting applied given the settings  that you are testing with. And is with mine. I'll send you the settings that I have, when I get back to my PC. You did enable the grey setting in the grid format admin settings didn't you?

**Comment by gjb2048** [comment]
Oh my bad!  Was making the section hidden instead!  However, having lots of issues with IE11 - does not grey out and the box alignment goes squiffy when there is no link.  I hate IE.

**Comment by gjb2048** [comment]
Please see latest master.

**Comment by justinhunt** [comment]
Oh really. Ok. I'll look at that.

**Comment by gjb2048** [comment]
e.g.:

2016-05-20 11_03_48-course_ grid - internet explorer

**Comment by justinhunt** [comment]
I left my windows machine on-site, so I will not be able to test this till
later next week when I return there.
J

**Comment by gjb2048** [comment]
Hi Justin,

Please see: https://github.com/gjb2048/moodle-format_grid/issues/31.

Gareth

**Comment by gjb2048** [comment]
Solution is bonkers: echo html_writer::tag('span', $content);

**Comment by justinhunt** [comment]
Ha! Well found. Sorry not to have sorted it out myself.

I have another tweak. It works ok for us,  but it would require a bit of
tidying and testing and generalising before release.
Basically it displays a "done" stamp on the grid icon for a section if all
the completable activities in the section are completed.

I don't think I will have the time to fix it up for general release. Let me
know if you want what we have so far though, and I will submit it.

Justin

**Pull request merged**
