### PR TITLE
added navdrawer functionality for #50

### PR DESCRIPTION
**Pull request by sharpchi**
#50 Fix for missing navdrawer functionality.

### CODE REVIEW

**Comment by gjb2048** [comment]
Note to self.  Code needs:

Travis CI issues fixed.
Functionality duplication refactored.
Change to use 'data-region="drawer"' instead of 'nav-drawer' id to be less theme specific - i.e. support Essential that needs to be updated to in M3.3.  Plus need to have a more specific selector to target the first 'nav'.

**Comment by gjb2048** [comment]
Oh how annoying, does not work with section 0.

**Comment by gjb2048** [comment]
Plus you forgot to add code to tab to the section that was opened.

**Comment by sharpchi** [comment]
Thoroughly enjoyed your conversation with yourself. Thanks for doing the update. Working OK my end.

**Pull request merged**
